IMPORTANDO LIBRERÍA NUMPY

In [ ]:
import numpy as np

Lista

In [ ]:
lista = list(range(1,11))
lista

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

Tansformando la lista a un Array

In [ ]:
arreglo = np.array(lista)
arreglo

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

Corroborando el tipo de objeto

In [ ]:
type(arreglo)


numpy.ndarray

In [ ]:
arreglo.dtype

dtype('int64')

Definiendo el array de int64 a *float32*

In [ ]:
np.array(arreglo, dtype=np.float64)

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

Sigue siendo un array de int64

In [ ]:
arreglo

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

Obteniendo el promedio del array

In [ ]:
promedio = np.mean(arreglo)
promedio

5.5

Obteniendo la mediana del array

In [ ]:
mediana = np.median(arreglo)
mediana

5.5

Desviación estandar del arreglo

In [ ]:
desviacion_std = np.std(arreglo)
desviacion_std

2.8722813232690143

GENERAR ARREGLO DE 10 ELEMENTOS DE SOLO UNOS UNO SOLO

In [ ]:
arreglonuevo = np.arange(1,11)
arreglonuevo

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

arreglo de 2 en 2 utilizando arange

In [ ]:
arreglonuevo2 = np.arange(1,11,2)
arreglonuevo2

array([1, 3, 5, 7, 9])

ALGUNAS FUNCIONES DE NUMPY

In [ ]:
arreglo_de_unos = np.zeros(5)
arreglo_de_unos

array([0., 0., 0., 0., 0.])

In [ ]:
arreglo_int_unos = arreglo_de_unos.astype

Obteniendo numeros aleatorios

In [ ]:
arreglo_aleatorio = np.random.rand(10)
arreglo_aleatorio

array([0.81906865, 0.09675313, 0.25387025, 0.54423402, 0.71820032,
       0.60631922, 0.66329021, 0.46150385, 0.52668911, 0.70330765])

Generando un arreglo de aleatorios de 10 numeros enteros del 1 al 5

UTILIZANDO LA FUNCION RANDOM

In [ ]:
arreglo_aleatorio2 = np.random.randint(1,6,10)
arreglo_aleatorio2

array([4, 5, 5, 5, 2, 5, 1, 3, 2, 1])

Matris aleatoria de 3x3

In [ ]:
matriz = np.random.rand(3,3)
matriz

array([[0.76478148, 0.0579292 , 0.17535373],
       [0.23014133, 0.98478409, 0.90695674],
       [0.42178087, 0.07290217, 0.51234552]])

Generando una matriz aleatoria de 10 numeros enteros del 1 al 100

In [ ]:
matriz2 = np.random.randint(1,100,(10,10))
matriz2

array([[73, 77, 76,  4, 36, 88, 82, 46, 32, 72],
       [56,  4, 52, 39, 79, 54, 88, 34, 93, 71],
       [33, 72, 10, 61, 25, 14, 38, 16, 76, 46],
       [19, 98, 96, 53, 90, 48, 18, 79, 65, 92],
       [13, 53, 75,  3, 21, 78, 30, 78, 69, 26],
       [83,  5, 21,  5, 99, 75, 41, 94, 85,  2],
       [71,  2, 44, 39, 17, 42, 31, 99, 20, 69],
       [19, 47, 66, 34, 70, 72, 94, 60, 11,  3],
       [63, 36, 91, 84, 98, 38, 11, 76, 59, 14],
       [27, 62, 86, 45, 12, 95, 38, 81, 51, 37]])