In [2]:
import numpy as np

DIMENSIONES

Generando un Array de 12 elementos enteros con Random

In [3]:
arreglo = np.random.randint(1,10,12)
arreglo

array([5, 4, 1, 7, 5, 4, 6, 5, 2, 8, 7, 8])

Obtener la dimensión de un arreglo

In [4]:
np.shape(arreglo)

(12,)

Transformación del vector de 9 elementos a Matriz 4x3 con  Reshape

In [5]:
matriz = arreglo.reshape(4,3)
matriz

array([[5, 4, 1],
       [7, 5, 4],
       [6, 5, 2],
       [8, 7, 8]])

Otra Transformación del vector de 9 elementos a matriz de 3x4 con reshape

In [6]:
matriz = arreglo.reshape(3,4)
matriz

array([[5, 4, 1, 7],
       [5, 4, 6, 5],
       [2, 8, 7, 8]])

Creando un Tensor

In [1]:
t = [[[[1,2,3],[4,5,6],[7,8,9],[1,2,3]]]]
t

[[[[1, 2, 3], [4, 5, 6], [7, 8, 9], [1, 2, 3]]]]