IMPORTANDO LIBRERÍA NUMPY

In [1]:
import numpy as np

Lista

In [2]:
lista = list(range(1,11))
lista

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

Tansformando la lista a un Array

In [3]:
arreglo = np.array(lista)
arreglo

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

Corroborando el tipo de objeto

In [4]:
type(arreglo)


numpy.ndarray

In [5]:
arreglo.dtype

dtype('int32')

Definiendo el array de int64 a *float32*

In [6]:
np.array(arreglo, dtype=np.float64)

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

Sigue siendo un array de int64

In [7]:
arreglo

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

Obteniendo el promedio del array

In [8]:
promedio = np.mean(arreglo)
promedio

5.5

Obteniendo la mediana del array

In [9]:
mediana = np.median(arreglo)
mediana

5.5

Desviación estandar del arreglo

In [10]:
desviacion_std = np.std(arreglo)
desviacion_std

2.8722813232690143

GENERAR ARREGLO DE 10 ELEMENTOS DE SOLO UNOS UNO SOLO

In [11]:
arreglonuevo = np.arange(1,11)
arreglonuevo

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

arreglo de 2 en 2 utilizando arange

In [12]:
arreglonuevo2 = np.arange(1,11,2)
arreglonuevo2

array([1, 3, 5, 7, 9])

ALGUNAS FUNCIONES DE NUMPY

In [13]:
arreglo_de_unos = np.zeros(5)
arreglo_de_unos

array([0., 0., 0., 0., 0.])

In [14]:
arreglo_int_unos = arreglo_de_unos.astype

Obteniendo numeros aleatorios

In [15]:
arreglo_aleatorio = np.random.rand(10)
arreglo_aleatorio

array([0.19812813, 0.12376236, 0.77319589, 0.1444995 , 0.25555886,
       0.59397825, 0.35588649, 0.21555733, 0.46299657, 0.13732026])

Generando un arreglo de aleatorios de 10 numeros enteros del 1 al 5

UTILIZANDO LA FUNCION RANDOM

In [16]:
arreglo_aleatorio2 = np.random.randint(1,6,10)
arreglo_aleatorio2

array([4, 5, 2, 1, 2, 5, 5, 1, 3, 5])

Matris aleatoria de 3x3

In [17]:
matriz = np.random.rand(3,3)
matriz

array([[0.40230412, 0.42467366, 0.22576229],
       [0.13812441, 0.35837089, 0.74436397],
       [0.89115044, 0.1329913 , 0.36587063]])

Generando una matriz aleatoria de 10 numeros enteros del 1 al 100

In [18]:
matriz2 = np.random.randint(1,100,(10,10))
matriz2

array([[53, 68, 87, 74, 83, 71, 24,  7, 64, 79],
       [25, 53, 87, 70, 88, 61, 23, 98, 77, 26],
       [40, 55, 77, 39, 55, 56, 64,  6, 28, 62],
       [53, 35, 16, 43, 53, 64, 33, 29, 91, 47],
       [ 2, 56, 51, 65,  4, 26, 86, 83, 20, 95],
       [52,  2,  1, 87, 78, 87, 68, 19, 50, 88],
       [28, 55, 77, 46,  8, 42, 47, 89, 15, 48],
       [ 6, 54, 37, 43, 86, 28, 46, 13, 14, 86],
       [98, 75, 80, 41, 52, 12, 48, 72,  6, 98],
       [30, 81, 26, 95, 69, 18, 38, 65, 19, 65]])