In [1]:
import numpy as np

DIMENSIONES

Generando un Array de 12 elementos enteros con Random

In [2]:
arreglo = np.random.randint(1,10,12)
arreglo

array([8, 3, 7, 2, 7, 1, 8, 6, 1, 2, 2, 9])

Obtener la dimensión de un arreglo

In [3]:
np.shape(arreglo)

(12,)

Transformación del vector de 9 elementos a Matriz 4x3 con  Reshape

In [4]:
matriz = arreglo.reshape(4,3)
matriz

array([[8, 3, 7],
       [2, 7, 1],
       [8, 6, 1],
       [2, 2, 9]])

Otra Transformación del vector de 9 elementos a matriz de 3x4 con reshape

In [5]:
matriz = arreglo.reshape(3,4)
matriz

array([[8, 3, 7, 2],
       [7, 1, 8, 6],
       [1, 2, 2, 9]])

Creando un Tensor

In [6]:
t = [[[[1,2,3],[4,5,6],[7,8,9],[1,2,3]]]]
t

[[[[1, 2, 3], [4, 5, 6], [7, 8, 9], [1, 2, 3]]]]